using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UIWidgetsGallery.gallery;
using Unity.UIWidgets.engine;
using Unity.UIWidgets.material;
using Unity.UIWidgets.painting;
using Unity.UIWidgets.rendering;
using Unity.UIWidgets.ui;
using Unity.UIWidgets.widgets;
using UnityEngine;

namespace uichat
{
  public class App : UIWidgetsPanel
  {
    /// Models that need to be available to the full scope of the app
    /// TODO: possibly move these into some sort of DI/SL container?
    public static UserModel UserModel = new UserModel();
    public static ProfilesModel ProfilesModel = new ProfilesModel();

    protected override void OnEnable()
    {
      FontManager.instance.addFont(Resources.Load<Font>("MaterialIcons-Regular"), "Material Icons");

      base.OnEnable();
    }

    protected override Widget createWidget()
    {
      //this.GenerateJSON();

      return new MaterialApp(
        home: new ConversationsScreen(), //new ChatScreen (friend: chatFriend),
        title: "UI Chat");
    }

    private void GenerateJSON()
    {
      List<int> ids = new List<int>
      {
        27,
        1,
        19,
        5,
        17,
        25,
        35,
        3,
        0,
        11,
        7,
        30,
        16,
        8,
        26,
        31,
        29,
        12,
        23,
        6,
        36,
        24,
        22,
        32,
        34,
        20,
        14,
        2,
        13,
        9
      };

      List<string> lyrics = new List<string>
      {
        "some",
        "body",
        "once",
        "told",
        "me",
        "the",
        "world",
        "is",
        "gonna",
        "roll",
        "me",
        "I",
        "ain't",
        "the",
        "sharpest",
        "tool",
        "in",
        "the",
        "shed",
        "she",
        "was",
        "looking",
        "kinda",
        "dumb",
        "with",
        "her",
        "finger",
        "and",
        "her",
        "thumb",
        "in",
        "shape",
        "of",
        "an",
        "L",
        "on",
        "her",
        "forehead",
        "well",
        "the",
        "years",
        "start",
        "coming",
        "and",
        "they",
        "don't",
        "stop",
        "coming",
        "fed",
        "to",
        "the",
        "rules",
        "and",
        "I",
        "hit",
        "the",
        "ground",
        "running",
        "didn't",
        "make",
        "sense",
        "not",
        "to",
        "live",
        "for",
        "fun",
        "your",
        "brain",
        "gets",
        "smart",
        "but",
        "your",
        "head",
        "gets",
        "dumb",
        "so",
        "much",
        "to",
        "do",
        "so",
        "much",
        "to",
        "see",
        "so",
        "what's",
        "wrong",
        "with",
        "taking",
        "the",
        "back",
        "street",
        "you'll",
        "never",
        "know",
        "if",
        "you",
        "don't",
        "go",
        "you'll",
        "never",
        "shine",
        "if",
        "you",
        "don't",
        "glow",
        "hey",
        "now",
        "you're",
        "an",
        "all",
        "star",
        "get",
        "your",
        "game",
        "on",
        "go",
        "play",
        "hey",
        "now",
        "you're",
        "a",
        "rock",
        "star",
        "get",
        "the",
        "show",
        "on",
        "get",
        "paid",
        "and",
        "all",
        "that",
        "glitters",
        "is",
        "gold",
        "only",
        "shooting",
        "stars",
        "break",
        "the",
        "mold",
        "it's",
        "a",
        "cool",
        "place",
        "and",
        "they",
        "say",
        "it",
        "gets",
        "colder",
        "you're",
        "bundled",
        "up",
        "now",
        "wait",
        "'til",
        "you",
        "get",
        "older",
        "but",
        "the",
        "meteor",
        "men",
        "beg",
        "to",
        "differ",
        "judging",
        "by",
        "the",
        "hole",
        "in",
        "the",
        "satellite",
        "picture",
        "the",
        "ice",
        "we",
        "skate",
        "is",
        "getting",
        "pretty",
        "thin",
        "the",
        "waters",
        "getting",
        "warm",
        "so",
        "you",
        "might",
        "as",
        "well",
        "swim",
        "my",
        "world's",
        "on",
        "fire",
        "how",
        "about",
        "yours",
        "that's",
        "the",
        "way",
        "I",
        "like",
        "it",
        "and",
        "I",
        "never",
        "get",
        "bored",
        "hey",
        "now",
        "you're",
        "an",
        "all",
        "star",
        "get",
        "your",
        "game",
        "on",
        "go",
        "play",
        "hey",
        "now",
        "you're",
        "a",
        "rock",
        "star",
        "get",
        "the",
        "show",
        "on",
        "get",
        "paid",
        "and",
        "all",
        "that",
        "glitters",
        "is",
        "gold",
        "only",
        "shooting",
        "stars",
        "break",
        "the",
        "mold",
        "hey",
        "now",
        "you're",
        "an",
        "all",
        "star",
        "get",
        "your",
        "game",
        "on",
        "go",
        "play",
        "hey",
        "now",
        "you're",
        "a",
        "rock",
        "star",
        "get",
        "the",
        "show",
        "on",
        "get",
        "paid",
        "and",
        "all",
        "that",
        "glitters",
        "is",
        "gold",
        "only",
        "shooting",
        "stars",
        "somebody",
        "once",
        "asked",
        "could",
        "you",
        "spare",
        "some",
        "change",
        "for",
        "gas",
        "I",
        "need",
        "to",
        "get",
        "myself",
        "away",
        "from",
        "this",
        "place",
        "I",
        "said",
        "yep",
        "what",
        "a",
        "concept",
        "I",
        "could",
        "use",
        "a",
        "little",
        "fuel",
        "myself",
        "and",
        "we",
        "could",
        "all",
        "use",
        "a",
        "little",
        "change",
        "well",
        "the",
        "years",
        "start",
        "coming",
        "and",
        "they",
        "don't",
        "stop",
        "coming",
        "fed",
        "to",
        "the",
        "rules",
        "and",
        "I",
        "hit",
        "the",
        "ground",
        "running.",
        "didn't",
        "make",
        "sense",
        "not",
        "to",
        "live",
        "for",
        "fun",
        "your",
        "brain",
        "gets",
        "smart",
        "but",
        "your",
        "head",
        "gets",
        "dumb",
        "so",
        "much",
        "to",
        "do",
        "so",
        "much",
        "to",
        "see",
        "so",
        "what's",
        "wrong",
        "with",
        "taking",
        "the",
        "back",
        "streets",
        "you'll",
        "never",
        "know",
        "if",
        "you",
        "don't",
        "go",
        "you'll",
        "never",
        "shine",
        "if",
        "you",
        "don't",
        "glow",
        "hey",
        "now",
        "you're",
        "an",
        "all",
        "star",
        "get",
        "your",
        "game",
        "on",
        "go",
        "play",
        "hey",
        "now",
        "you're",
        "a",
        "rock",
        "star",
        "get",
        "the",
        "show",
        "on",
        "get",
        "paid",
        "and",
        "all",
        "that",
        "glitters",
        "is",
        "gold",
        "only",
        "shooting",
        "stars",
        "break",
        "the",
        "mold",
        "and",
        "all",
        "that",
        "glitters",
        "is",
        "gold",
        "only",
        "shooting",
        "stars",
        "break",
        "the",
        "mold",
      };


      lyrics.Reverse();

      for (int i = 0; i < ids.Count; i++)
      {
	      List<string> output = new List<string>();
        int otherId = ids[i];
        int userId = UserModel.Profile.Id;

        System.Random r = new System.Random();

        DateTime from = DateTime.Now;
        from.AddDays(-3);

        DateTime dt = GetDT(from, DateTime.Now);

        output.Add("{ \"Data\": [");
        
        for (int j = 0; j < lyrics.Count; j++)
        {
          int id = r.Next() % 2 == 0 ? otherId : userId;

          string body = lyrics[j];

          string convoJSON = $"{{ \"Sender\": {id}, \"Body\": \"{body}\", \"TimeStamp\": \"{dt}\" }}";

          if(j < lyrics.Count-1)
          {
            convoJSON += ",";
          }
          
          output.Add(convoJSON);
        }
        output.Add("]}");

		string path = $"Assets/Resources/{otherId}.json.txt";

		////Write some text to the test.txt file
		//StreamWriter writer = new StreamWriter(path, true);
		//writer.WriteLine(string.Join("", output));

		//writer.Close();

				File.WriteAllText(path, string.Join("", output));
      }

    }

    private DateTime GetDT(DateTime from, DateTime to)
    {
      System.Random r = new System.Random();

      var range = to - from;

      var randTimeSpan = new TimeSpan((long) (r.NextDouble() * range.Ticks));

      return from + randTimeSpan;
    }
  }
}